### ISSUE TITLE
Add "copy link" feature

### ISSUE THREAD

**Issue by loreguerra** [fcurella/django-social-share#12]
Commonly seen across other share button sets.

**Comment by karki011** [comment]
If no one has taken this, I want to try this issue.

**Comment by fcurella** [comment]
Thank you @karki011 ! I'm assigning you the issue :)

**Comment by goromachine** [comment]
Any news regarding this issue? It would be very nice to have on the same package :)

**Comment by fcurella** [comment]
@baxeico nobody submitted a Pull Request yet. @karki011 are you still available?

**Comment by Barissa-Imran** [comment]
feature added
