### ISSUE TITLE
Overriding the template

### ISSUE THREAD

**Issue by latusaki** [fcurella/django-social-share#4]
How can I override the template, so that I only retrieve the href, as opposed to the whole anchor tag? I am new to django and not sure where to start.

**Comment by latusaki** [comment]
I guess this is more of an SO question than a git question.

**Comment by prafulbagai** [comment]
Were you able to override the template?

**Comment by latusaki** [comment]
Its been over a year, so I am not going to dig in too much.. I have a template tag that only has 
`{{ facebook_url }}` inside, then using that in my main page as 
`<a href="{% post_to_twitter post.title post %}"title="Share on Twitter" target="_blank" class="btn-sm btn-twitter"><i class="fa fa-twitter"></i> Tweet</a>`.
Feel free to dig in, keep in mind that was my first django project :P 
https://github.com/latusaki/googleappengine-djangae-blog

**Comment by LaundroMat** [comment]
For anyone who stumbles on this via Google: the [Django docs](https://docs.djangoproject.com/en/2.1/howto/overriding-templates/) explain quite well how to override app templates.
