### ISSUE TITLE
Add "pinterest" share feature.

### ISSUE THREAD

**Issue by amlido** [fcurella/django-social-share#42]
Commonly sharing plate-form and also seen many places.

**Comment by fcurella** [comment]
Could you start a Pull Request?

**Comment by brian101co** [comment]
Hey, if no one is currently working on this feature request I plan to make a PR and work on it. Is it available?

**Comment by fcurella** [comment]
Sure, go for it, @brian101co

**Comment by AlanSwenson** [comment]
should this be closed now based on #50 ?
