### ISSUE TITLE
Django-social-share Links Inside Icons.

### ISSUE THREAD

**Issue by claytonseraphin** [fcurella/django-social-share#43]
I'm actually using social-share library on django, and I can't find any way to insert the sharing link inside icons like font awesome. Anything I'm missing or you built it like that?

**Comment by fcurella** [comment]
Hi!

You can use something like `{% post_to_twitter_url <text_to_post> <object_or_url> %}` to populate a `tweet_url` variable in your context:

```
{% post_to_twitter_url "Check this out" "https://example.com" %}

<i class="fab fa-twitter"><a href="{ twitter_url }">Tweet this</a></i>
```

You can also use variables instead of strings:

```
{% post_to_twitter_url object.description object.get_absolute_url %}

<i class="fab fa-twitter"><a href="{ twitter_url }">Tweet this</a></i>
```

**Comment by claytonseraphin** [comment]
By changing post_to_twitter to post_to_twitter_url, it gave me this error that i attached as a screenshot below
![Screen Shot 2020-07-14 at 10 33 35 AM](https://user-images.githubusercontent.com/12686262/87438780-f948a580-c5bd-11ea-9a21-d09c8c47945c.png).
 And, "Post to Twitter" is by default, which means even if i remove the whole string, it still gives the default string, unless i replace it by something else, and that something i'd like it to be a font awesome icon. 
.

**Comment by fcurella** [comment]
@claytonseraphin Sorry, I had a typo in my example. you need to use _double_ curly braces in the `href`:

```
{% post_to_twitter_url object.description object.get_absolute_url %}

<i class="fab fa-twitter"><a href="{{ twitter_url }}">Tweet this</a></i>
```

**Comment by claytonseraphin** [comment]
post_to_twitter_url instead of post_to twitter, sill gave me that error. And the double curly braces don't really change the situation, the default "Post to Twitter" string is still displayed with the good link that should sent me to twitter. The icon should have had the link to send me to twitter.

**Comment by fcurella** [comment]
Can you try `{{ tweet_url }}` instead of `{{ twitter_url }}`?

**Comment by claytonseraphin** [comment]
I got it now, and i tried to trick it a way not to have the default string display by leaving a space between the quotation marks. And the, putting the font awesome class inside the a tag:
```
				{% post_to_twitter "New Product: {{products.name}}" products.get_absolute_url " " %}	
				<a href="{{ tweet_url }}"><i class="fa fa-twitter"></i></a>

				{% post_to_facebook products.get_absolute_url " " %}
				<a href="{{ facebook_url }}"><i class="fa fa-facebook-square"></i></a>
```

**Comment by claytonseraphin** [comment]
One more thing, wee need a variable for email as well, so we can avoid the default message just like tweet_url.

**Comment by fcurella** [comment]
@claytonseraphin I'm not sure I'm following. Do you need two different values for `{{ tweet_url }}` in the same template file?

If that's the case, you can just call `{% post_to_twitter_url %} a second time and it should override the value from that point on.

**Comment by learnICT** [comment]
I feel like this has been answered

https://github.com/fcurella/django-social-share/pull/6

**Comment by fcurella** [comment]
Thank you for triaging, @learnICT

**Comment by WillieIlus** [comment]
{% post_to_facebook object_or_url "<i class='fab fa-facebook-f'></i>" %}
                  {% post_to_twitter "{{post.title}}. Check it out!" object_or_url "<i class='fab fa-twitter'></i>" %}
                  {% post_to_whatsapp object_or_url "<i class='fab fa-whatsapp'></i>" %}
                  {% post_to_linkedin object_or_url "" "<i class='fab fa-linkedin'></i>" %}

this is how I implement mine, to accommodate font awesome.
