### ISSUE TITLE
[SOLVED] Sharer not share post, but facebook itself instead.

### ISSUE THREAD

**Issue by alzearafat** [fcurella/django-social-share#5]
Hi,

Nice plugin, but I have some problem, please bear with me.
Why sharer button not share post title & link, but facebook itself instead? Please have a look : 

![alt text](http://i64.tinypic.com/28ul446.jpg "Logo Title Text 1")

![alt text](http://i66.tinypic.com/f0zpeg.jpg "Logo Title Text 1")

*Bagikan = Share*

And this is my code : 

```
{% post_to_facebook object_or_url "Facebook" %}

{% post_to_twitter "New Journey: {{object.title}}. Check it out!" object_or_url "Twitter" %}

{% post_to_gplus object_or_url "Google+" %}
```

Please excuse my English :)

Thanks in advance!
Regards

**Comment by fcurella** [comment]
hi @alzearafat,

can you post the full URL that the template tag is generating?

**Comment by fcurella** [comment]
@alzearafat It's probably due to the fact that you're sharing something on `localhost:8000`, which the facebook page can not access. Try sharing something with a publicly accessible URL

**Comment by alzearafat** [comment]
Hi,

Yes, you are right. It's solved now, thank you! :D 

@fcurella
