### ISSUE TITLE
ModuleNotFoundError: No module named 'django-social-share'

### ISSUE THREAD

**Issue by MahdiJafari1** [fcurella/django-social-share#62]
After installing the package I got this error: 

`ModuleNotFoundError: No module named 'django-social-share'`

I followed the instruction on documentation. 
how to solve this issue?

**Comment by fcurella** [comment]
The module is called `django_social_share`, with underscores, so I'm a little confused.

Could you post the full stacktrace?

**Comment by MahdiJafari1** [comment]
I tried to install using `pip install django-social-share` and `pip3 install django-social-share` but the error was remaining. then I tried this: 
`sudo pip install django-social-share` and re-activate virtual environment (source /usr/bin/evnv/activate) and it worked!

**Comment by fcurella** [comment]
@MahdiJafari1 you really should not run `pip install` with `sudo`. That will install the package in your global environment, which is not what you want.

I also see you have a virtualenv inside `/usr/bin/`, which is very, very wrong.

What you should do is something like this:

```
# remove previous system-wide install
sudo pip uninstall django-social-share

# delete that environment that shouldn't be there
rm -rf /usr/bin/evnv/

cd <your project>

# create new virtualenv, outside of `/usr/bin/`.
# I find it convenient to make it inside the project, but could be anywhere in your _home_ directory.
python3 -m venv ./venv

# activate the new virtualenv
source venv/bin/activate

# use the virtualenv's pip to install the package
python3 -m pip install django-social-share
```

**Comment by MahdiJafari1** [comment]
Oh, I didn't know about that. @fcurella, I will do your recommendations. Thank you very much!
